# Generated by Django 5.0.1 on 2024-01-15 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='email',
        ),
        migrations.AddField(
            model_name='appuser',
            name='roleEnum',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
