# Generated by Django 5.0.1 on 2024-01-15 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_appuser_email_appuser_roleenum'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
    ]
