# Generated by Django 5.0.1 on 2024-06-11 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userItem', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useritem',
            old_name='quantity',
            new_name='ordered_quantity',
        ),
    ]
