# Generated by Django 5.0.1 on 2024-06-13 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userItem', '0002_rename_quantity_useritem_ordered_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='useritem',
            name='isPurchased',
            field=models.BooleanField(default=False),
        ),
    ]
