# Generated by Django 5.0.1 on 2024-06-15 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userItem', '0004_useritem_ispriceupdated_useritem_previousprice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useritem',
            name='isPriceUpdated',
        ),
        migrations.RemoveField(
            model_name='useritem',
            name='previousPrice',
        ),
        migrations.AlterField(
            model_name='useritem',
            name='isPurchased',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
