# Generated by Django 5.0.1 on 2024-06-16 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userItem', '0005_remove_useritem_ispriceupdated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useritem',
            name='isPriceUpdated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='useritem',
            name='previousPrice',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
