# Generated by Django 5.0.1 on 2024-06-22 00:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_alter_item_created_by'),
        ('userItem', '0006_useritem_ispriceupdated_useritem_previousprice'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='useritem',
            unique_together={('user', 'item', 'isPurchased')},
        ),
    ]
