# Generated by Django 5.0.1 on 2024-06-22 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userItem', '0007_alter_useritem_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='useritem',
            unique_together=set(),
        ),
    ]
